# Generated by Django 5.1.7 on 2025-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Usuarios",
        ),
    ]
